# Main config for NoAdvertisings
# Don't Change It!
config-version: 0.0.4
# Set it to true if you want it to automatically notify the console when a new update is available.
Update-notice: true
# Message when players advertise
Message: "Please don't advertise this thanks."
# Messages when adding domain
Domain-exists: "That domain already exist!."
Domain-added-successfully: "Successfully added {domain} into config."
# Messages when removing domain
Domain-not-exists: "That domain not exist!."
Domain-removed-successfully: "Successfully removed {domain} from config."
# The domains that allowed to use
allowed:
  - "funworld.world"

banned:
- "chooseips"

# Lines that will change if player advertise on sign
lines:
  - '============='
  - 'No AdvertisingCCC!'
  - ''
# The command that will protected from advertising
blocked.cmd:
  - "/me"
  - "/tell"
  - "/w"
  
